# Generated by Django 5.2.3 on 2025-07-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_organization_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('employee_id', 'organization'), ('username', 'organization')},
        ),
    ]
